### ISSUE TITLE
Installation from Repo Instructions Issue

### ISSUE THREAD

**Issue by EricaEgg** [p-ortmann/dyntapy#1]
I am able to install the package from conda-forge perfectly. However, I also tried following the "from this repository" instructions, and ran into issues. I cloned the repo and created the conda environment using the environment.yml file. After activating the environment, I ran the code `python -m pip install -e path-to-folder` but received the following error: `
ERROR: path-to-folder is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).` 
Did I interpret the instruction incorrectly?

**Comment by p-ortmann** [comment]
Thank you for reporting this!
You are meant to insert the path to the local copy of the repository which contains the setup.py file used by pip. I've updated the readme.md to point this out more clearly. See a4ea644a4299e844b113bf44905fd4bbca70cbc4

**Comment by EricaEgg** [comment]
Perfect! That worked. Thanks for the edit.
