### ISSUE TITLE
Overloading local infrastructure DTA

### ISSUE THREAD

**Issue by zhilee2019** [p-ortmann/dyntapy#3]
Hi Paul:

It's me again. I always have the overload issue. The sioux falls toy network was used and 22 centroids are created, About 80 od pairs every 5 minutes were created and I came accross the following waring. I added more centorids but didn't work. 

![1660892220039](https://user-images.githubusercontent.com/57939384/185561740-2a8baabc-1768-41ee-9d16-ca6125ec2bba.png)

**Comment by p-ortmann** [comment]
Hello, 

thanks for reporting this.
There's no support for spillback from the network onto connectors in the DTA routines. It's not trivial to deal with in the equilibration. 
You can either lower your demand or try to add more connectors to solve this.

**Comment by zhilee2019** [comment]
Thanks! I found that 'incremental_assignment’ method works well with massive demand. However, it raises the following issues. What does that means ? @p-ortmann 

![Uploading 1660901353358.png…]()

**Comment by p-ortmann** [comment]
Thanks for reporting!
it's a missing wrapper function, I've fixed this here: https://github.com/p-ortmann/dyntapy/commit/2e4ef18c6584c914b18d06a2b777f095f2d1cb3d it's now also part of the tests.

**Comment by zhilee2019** [comment]
Great that solves the issue perfectly!
