### ISSUE TITLE
 NumbaWarning: Cannot cache compiled function "i_ltm_aon_setup"

### ISSUE THREAD

**Issue by zhilee2019** [p-ortmann/dyntapy#4]
Hi Paul:

I have the following warnings. What should I do in order to cache compiled function "i_ltm_aon_setup" ?
![e15a98fc023fd9e961d08698d17ec0b](https://user-images.githubusercontent.com/57939384/185614319-a2646b51-fb2e-4a78-9559-6fd607d58602.png)

**Comment by p-ortmann** [comment]
dyntapy makes use of jitclasses, which, as of now, cannot be cached. https://github.com/numba/numba/issues/4830 There probably is a way to make struct refs work for dyntapy as well, but it would be a rather big overhaul. 

If all you want to do is quickly experiment on some small toy networks disabling compilation may be faster for you. To do so you just need to disable JIT compilation, like shown below. Note that this needs to be done before any other import statements

``` 
from numba import config
config.DISABLE_JIT=1
``` 
See https://numba.readthedocs.io/en/stable/reference/envvars.html for more details.
