### ISSUE TITLE
Simple toy example

### ISSUE THREAD

**Issue by finnwiz** [p-ortmann/dyntapy#7]
Hi there. Firstly, thank you for making this incredible repo - it has all sorts of neat stuff!

As a total beginner in this space, I'm trying to set up a super basic traffic assignment problem and solve it with Algorithm B ("dial_b") - but I think I'm getting a bit confused on (what I perceive as) the need for centroids and/or connectors in my simple problem.

I just wanted to load up a toy network...

```
# make the transport graph
g = dyntapy.supply_data.get_toy_network('cascetta')
# add required node attributes https://dyntapy.readthedocs.io/en/latest/dyntapy.html#module-dyntapy.assignments
nx.set_node_attributes(g,{i:i-1 for i in range(len(g.nodes)+1)},name="node_id")

# add required edge attributes
nx.set_edge_attributes(g,{(u,v):u-1 for u,v in g.edges},name="from_node_id")
nx.set_edge_attributes(g,{(u,v):v-1 for u,v in g.edges},name="to_node_id")
nx.set_edge_attributes(g,{(u,v):idx for idx,(u,v) in enumerate(g.edges)},name="link_id")

nx.draw(g,with_labels=True)
```
![download](https://github.com/p-ortmann/dyntapy/assets/136125357/0be6fb56-aea8-4f4a-8cb4-4c8f842bbee0)

And (this might be where I'm going wrong), I can set up an od_graph (effectively a flow of 3000 from 1->4):

```
od_graph = nx.DiGraph()
od_graph.add_nodes_from(g.nodes(data=True))
od_graph.add_edges_from([(1,4,{'flow':3000.0})])
```

I can then successfully set up the `StaticAssignment` object:

```
sa = dyntapy.assignments.StaticAssignment(g, od_graph)
```

But when I try to run:
``` 
result = sa.run(method='dial_b')
```

I get:

```
File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\dyntapy\sta\equilibrate_bush.py:775, in _update_trees()
    771 """
    772 k
    773 """
    774 assert k >= 0
--> 775 assert k <= len(topological_order) - 1
    776 assert n > 0
    777 assert n <= len(topological_order)

AssertionError: 
```

Am I misunderstanding the `od_graph` requirements? Am I actively mis-numbering something? Apologies for the confusion but appreciate any help...

I'm happy to make a PR on a fork of the repo with a simple notebook example once this is done (if that makes helping inexperienced folks any more palatable)...

**Comment by p-ortmann** [comment]
Hi finnwiz,

I am glad to hear you're finding this package useful! Admittedly, setting up toy networks from scratch is a bit finicky; however, the process becomes less cumbersome if you use the relabelling and centroid functionality provided in the package:

```
import numpy as np
from dyntapy import get_toy_network
from dyntapy.visualization import show_network, show_demand
from dyntapy.supply_data import relabel_graph
from dyntapy.demand_data import od_graph_from_matrix, add_centroids

# to set up the network
g = get_toy_network('cascetta')
centroid_x = np.array([1, 7, 4])
centroid_y = np.array([1, 1, 3.5])
g = add_centroids(g, centroid_x, centroid_y, euclidean=True)
# also adds connectors automatically
g = relabel_graph(g)  # adding link and node ids, connectors and centroids
# are the first elements
show_network(g, euclidean=True)

# and for the demand

od_matrix = np.zeros(9).reshape((3, 3))
od_matrix[0, 1] = 500
od_matrix[2, 1] = 500
od_graph = od_graph_from_matrix(od_matrix, centroid_x, centroid_y)
show_demand(od_graph, euclidean=True)
```

The above excerpt is taken from the dynamic assignment notebook in the tutorials. 

Looking at the documentation now, I see that neither the ```relabel_graph``` nor the ``` add_centroids``` function are mentioned in the assignment documentation, which is misleading - I'll add this in the next few days.

Hope this helps!

Cheers,
Paul

**Comment by finnwiz** [comment]
Thank you! It certainly does. I didn't dive into the dynamic assignment notebook because I was looking at static assignment. 

So, effectively, all of the OD flows are specified at the centroid level (vs. directly on the node-link) graph; and it's easier to just use the convenience functions to add centroids (and connectors) to the node-link graph, after which it looks like I can solve this static assignment problem using "dial_b". Yay.

Much appreciated; and if it is worth me adding a simple notebook to show this, just let me know.
